### ISSUE TITLE
Anchor Texture (Bug???)

### ISSUE THREAD

**Issue by Marz404** [HerobaneNair/herosanchoroptimizer#1]
Not entirely sure if this would be considered an issue but when you blow up the anchor during the fade out the original anchor texture shows. This happened while around 60-80ms I have no idea if it happens on any lower ping yet.
This isn't a major problem but can look a bit odd when using packs that change the way anchors look.

_**A bit difficult to see but i tried to get a screenshot and video** (video & screenshot taken on east.uspvp.org)_

![{3BC5F4DA-60D6-4ED7-B1F0-60D26A67D1BB}](https://github.com/user-attachments/assets/9ec67a9f-435e-45ef-b432-b0d633ccb283)

https://github.com/user-attachments/assets/60a1ca8e-0323-422e-9fd3-c11f29687013

**Comment by HerobaneNair** [comment]
Yes that's intended as a placeholder to be visible. I do have plans on making it work with packs but currently it'll keep looking that way. If you don't like it you can change the textures in assets/herosanchoroptimizer/textures or change the model of fake_anchor to be of a respawn anchor
